In [9]:
#1-D array
import numpy as np
oneD_array=np.array([1,2,3])
print(oneD_array)

[1 2 3]


In [14]:
#2-D array
twoD_array=np.array([[1,2,3],[4,5,6]])
print(twoD_array)

[[1 2 3]
 [4 5 6]]


In [15]:
#3-D array
twoD_array=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(twoD_array)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [4]:
#create an array with ones
import numpy as np
array_ones=np.ones((2,4))
print("array with ones: ",array_ones)#print a 2d array with four elements


array with ones:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
#create an arrays with zeros
array_zeros=np.zeros((3,3))
print("array_zeos :",array_zeros)

array_zeos : [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
#create an array with a particular range
array_range=np.arange(10)
print("array with a range :", array_range)

array with a range : [0 1 2 3 4 5 6 7 8 9]
