In [1]:
#1. Counts the number of non-zero values in the array
import numpy as np
arr = np.array([0, 2, 3, 0, 5, 6, 0, 8])
non_zero_count = np.count_nonzero(arr)
print(non_zero_count)


5


In [2]:
#2.How to create an empty and a full NumPy array?
empty_array = np.empty((3, 3))
print("Empty array:\n", empty_array)
full_array = np.full((3, 3), 7)
print("Full array:\n", full_array)


Empty array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Full array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [3]:
#3. Find the number of rows and columns of a given matrix using NumPy
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows, cols = matrix.shape
print("Rows:", rows, "Columns:", cols)


Rows: 3 Columns: 3


In [4]:
#4.Find the sum of values in a matrix
matrix_sum = np.sum(matrix)
print("Sum of matrix values:", matrix_sum)


Sum of matrix values: 45


In [5]:
#5.Calculate the sum of the diagonal elements of a NumPy array 3*3 and 4*4
#3x3 matrix
matrix_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Sum of diagonal elements
diag_sum_3x3 = np.trace(matrix_3x3)
print("Sum of diagonal elements (3x3):", diag_sum_3x3)
#4x4 matrix
matrix_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
# Sum of diagonal elements
diag_sum_4x4 = np.trace(matrix_4x4)
print("Sum of diagonal elements (4x4):", diag_sum_4x4)


Sum of diagonal elements (3x3): 15
Sum of diagonal elements (4x4): 34


In [6]:
#6. How to inverse a matrix using NumPy
matrix_to_inverse = np.array([[1, 2], [3, 4]])
matrix_inverse = np.linalg.inv(matrix_to_inverse)
print("Inverse of the matrix:\n", matrix_inverse)


Inverse of the matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [7]:
#7. Matrix Multiplication in NumPy
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(matrix_a, matrix_b)
print("Matrix multiplication result:\n", matrix_product)


Matrix multiplication result:
 [[19 22]
 [43 50]]


In [8]:
#8. Get the maximum and minimum value from given matrix
max_value = np.max(matrix)
print("Maximum value:", max_value)
min_value = np.min(matrix)
print("Minimum value:", min_value)


Maximum value: 9
Minimum value: 1


In [9]:
#9. Adding and Subtracting Matrices in Python.
# Addition
matrix_sum = np.add(matrix_a, matrix_b)
print("Sum of matrices:\n", matrix_sum)
# Subtraction
matrix_diff = np.subtract(matrix_a, matrix_b)
print("Difference of matrices:\n", matrix_diff)


Sum of matrices:
 [[ 6  8]
 [10 12]]
Difference of matrices:
 [[-4 -4]
 [-4 -4]]


In [10]:
#10. How to count the frequency of unique values in NumPy array?
array = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
# Count frequency of unique values
unique, counts = np.unique(array, return_counts=True)
frequency = dict(zip(unique, counts))
print("Frequency of unique values:\n", frequency)


Frequency of unique values:
 {1: 1, 2: 2, 3: 3, 4: 4}
