In [ ]:
#1.Make a copy, change the original array, and display both arrays
import numpy as np
orginal_array=np.array([[10,11,12],[13,14,15]])
print("The Orginal Array is : ",orginal_array)
copy_array=orginal_array.copy()
print("The Copied Array is : ",copy_array)
orginal_array[1,0]=20
print("The Orginal Array after Modification is : ",orginal_array)

In [41]:
#2.Make a view, change the original array, and display both arrays
print("The Orginal Array is : ",orginal_array)
view_array=orginal_array.view()
print("The View Array is : ",view_array)
orginal_array[0,0]=30
print("The Modified Orginal Array is : ",orginal_array)


The Orginal Array is :  [[10 11 12]
 [20 14 15]]
The View Array is :  [[10 11 12]
 [20 14 15]]
The Modified Orginal Array is :  [[30 11 12]
 [20 14 15]]


In [42]:
#3.Make a view, change the view, and display both arrays
print("The Orginal Array is : ", orginal_array)
view_array=orginal_array.view()
print("The View Array is : ", view_array)
view_array[1,0]=10
print("The Modified View Array is : ", view_array)
print("Orginal array after view Modification is : ",orginal_array)

The Orginal Array is :  [[30 11 12]
 [20 14 15]]
The View Array is :  [[30 11 12]
 [20 14 15]]
The Modified View Array is :  [[30 11 12]
 [10 14 15]]
Orginal array after view Modification is :  [[30 11 12]
 [10 14 15]]


In [44]:
#4.Print the value of the base attribute to check if an array owns it's data or not
print("Original Array base:", orginal_array.base)
print("Copied Array base:", copy_array.base)
print("View Array base:", view_array.base)


Original Array base: None
Copied Array base: None
View Array base: [[30 11 12]
 [10 14 15]]
