In [ ]:
#Iteration
  #loop used iteration inside an array or list in py - for-in loop


In [2]:
#1-D Array
import numpy as np
array_1D=np.array([1,2,3,4,5,6])
print("Array_1D : ",array_1D)
#iterating each element in this array
for elements in array_1D:
    print(elements)

Array_1D :  [1 2 3 4 5 6]
1
2
3
4
5
6


In [12]:
#2-D Array
array_2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array_2D : ",array_2D)
#iterating element in a 2-Darray
for row in array_2D:
#iterating each element in a 2-D array -nested forloop 
    print(row)
for elements in row:
    print(elements)

Array_2D :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[4 5 6]
[7 8 9]
7
8
9


In [14]:
#method used for iteration in multidimensional array without adding nested loop -np.nditer()
for elements in np.nditer(array_2D):
    print(elements)

1
2
3
4
5
6
7
8
9


In [16]:
#Iterating each elements with index values
  #method - np.ndenumerate()
for Index,elements in np.ndenumerate(array_2D):
    print(f"Index :{Index}, Elements : {elements}")

Index :(0, 0), Elements : 1
Index :(0, 1), Elements : 2
Index :(0, 2), Elements : 3
Index :(1, 0), Elements : 4
Index :(1, 1), Elements : 5
Index :(1, 2), Elements : 6
Index :(2, 0), Elements : 7
Index :(2, 1), Elements : 8
Index :(2, 2), Elements : 9
