In [ ]:
#Array join

In [2]:
#1.Concatenate() - for 1 D
import numpy as np
array1=np.array([1,2,3])
array2=np.array([4,5,6])
concat_array=np.concatenate((array1,array2))
print("The concatenated array is : ",concat_array)

The concatenated array is :  [1 2 3 4 5 6]


In [3]:
#2. 2-D array/multi_D -
array2d_1=np.array([[1,2,3],[4,5,6]])
array2d_2=np.array([[7,8,9],[10,11,12],[13,14,15]])
#joining vertically and Horizontally
 #verical method - vstack
 #horizontal method - hstack
#vstack
vstack_array=np.vstack((array2d_1,array2d_2))
print("Vertical stacked array is : ",vstack_array)



Vertical stacked array is :  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [5]:
#hstack -work only if the two arrays are of same dimension
array2d_1=np.array([[1,2,3],[4,5,6]])
array2d_2=np.array([[7,8,9],[10,11,12]])
hstack_array=np.hstack((array2d_1,array2d_2))
print("Horizontally stacked array is : ",hstack_array)

Horizontally stacked array is :  [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
