In [ ]:
#Reshaping arrays
  #method used - .reshape()
#shape of an array
  #method - .shape

In [7]:
#1D to 2D
import numpy as np
array_1D=np.array([3,4,5,6,7,8,])
print('One Dimensional array is : ',array_1D)
print('Shape of the one Dimensional array is : ',array_1D.shape)
array_2D=array_1D.reshape((2,3))
print('Two Dimensional array is : ',array_2D)
print('Shape of the Two Dimensional array is : ',array_2D.shape)

One Dimensional array is :  [3 4 5 6 7 8]
Shape of the one Dimensional array is :  (6,)
Two Dimensional array is :  [[3 4 5]
 [6 7 8]]
Shape of the Two Dimensional array is :  (2, 3)


In [9]:
#1D to 3D
array_3D=array_1D.reshape((3,2))
print('Three Dimensional array is : ',array_3D)
print('Shape of the Three  Dimensional array is : ',array_3D.shape)

Three Dimensional array is :  [[3 4]
 [5 6]
 [7 8]]
Shape of the Three  Dimensional array is :  (3, 2)


In [10]:
array_3D=array_1D.reshape((3,2,1))
print('Three Dimensional array is : ',array_3D)
print('Shape of the Three  Dimensional array is : ',array_3D.shape)

Three Dimensional array is :  [[[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]
Shape of the Three  Dimensional array is :  (3, 2, 1)


In [14]:
#2D to 1D
array_1D_back=array_2D.reshape((-1))
print('The one Dimensional array is : ',array_1D_back)
print('Shape of the one Dimensional array is : ',array_1D_back.shape)

The one Dimensional array is :  [3 4 5 6 7 8]
Shape of the one Dimensional array is :  (6,)


In [15]:
#2D to 1D another method
array_1D_back=array_2D.reshape((6))
print('The one Dimensional array is : ',array_1D_back)
print('Shape of the one Dimensional array is : ',array_1D_back.shape)

The one Dimensional array is :  [3 4 5 6 7 8]
Shape of the one Dimensional array is :  (6,)
