In [22]:
#1.Print the shape of a 2-D array
import numpy as np
array_2_D=np.array([[1,2,3],[4,5,6],[20,30,40]])
array_2_D_shape=array_2_D.shape
print("The shape of the Two Dimensioanl Array is : ",array_2_D_shape)

The shape of the Two Dimensioanl Array is :  (3, 3)


In [23]:
#2.Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4
array = np.array([1, 2, 3, 4], ndmin=5)
print("The array of dimension 5 is : ",array)
array_last_dimension = array[-1,-1,-1,-1,-1]
print("The value of array of last dimension is : ",array_last_dimension)

The array of dimension 5 is :  [[[[[1 2 3 4]]]]]
The value of array of last dimension is :  4


In [24]:
#3.Convert the following 1-D array with 12 elements into a 2-D array. The outermost dimension will have 4 arrays, each with 3 elements:
array_1D=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("The 1-D array of 12 elements is : ",array_1D)
array_2D=array_1D.reshape(4,3)
print("The 2-D array of dimension 4  with 3 elements each is : ",array_2D)


The 1-D array of 12 elements is :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
The 2-D array of dimension 4  with 3 elements each is :  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [25]:
#4.Convert the following 1-D array with 12 elements into a 3-D array. The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements
array_3D=array_1D.reshape(2,3,2)
print("The 3-D array  is : ",array_3D)

The 3-D array  is :  [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [26]:
#5.Check if the returned array is a copy or a view
print("The orginal or 1D array is : ",array_1D)
array_view = array_1D.reshape(4, 3)
array_copy = array_1D.reshape(4, 3).copy()
print("Is the reshaped array a view? ", array_view.base is array_1D)
print("The view array is : ",array_view)
print("Is the reshaped array a copy? ", array_copy.base is array_1D)
print("The view array is : ",array_copy)

The orginal or 1D array is :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Is the reshaped array a view?  True
The view array is :  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Is the reshaped array a copy?  False
The view array is :  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
