In [16]:
#1.Get third and fourth elements from an array and add them
import numpy as np
array=np.array([1,2,3,4,5])
get_third_element=array[3]
get_fourth_element=array[4]
print("The third element is : ",get_third_element)
print("The fourth element is : ",get_fourth_element)
add=get_third_element+get_fourth_element
print(' And Their sum  is :',add)

The third element is :  4
The fourth element is :  5
 And Their sum  is : 9


In [21]:
#2.Access the element on the 2nd row, 5th column in the array
import numpy as np
array=np.array([[1,2,3,4,5,6,],[7,8,9,10,11,12],[8,9,6,11,23,56]])
get_element_2ndrow=array[2,:]
get_elements_5thcolm=array[:,5]
print(get_element_2ndrow)
print(get_elements_5thcolm)

[ 8  9  6 11 23 56]
[ 6 12 56]


In [31]:
#3.Access the third element of the second array of the first array
arr = np.array([[1, 2, 3, 4, 0], [5, 6, 7, 8, 9]])
element = arr[1, 3]
print(element)

9


In [24]:
#4.Slice elements from the beginning to index 4 (not included)
array=np.array([5,8,0,7,10])
slice_element=array[:-1]
print(slice_element)

[5 8 0 7]


In [28]:
#5.Slice from the index 3 from the end to index 1 from the end
array=np.array([12,24,36,48,60])
Index_3_1=array[-3:-1]
print(Index_3_1)

[36 48]
